const events=[
 {name:"Sandbox Music Festival ’26",desc:"World-class artists, immersive production and one of Melbourne’s most iconic warehouse venues transformed into a festival playground.",image:"photo-1506157786151-b8491531f063",tag:"FESTIVAL · MELBOURNE",soldOut:true}
];
const past=[
 ["Four To Eight at The Substation","A sold-out show at The Substation with Four To Eight.","assets/media/fourtoeight-01.jpg"],
 ["Doruksen’s Melbourne Show","Our biggest show yet, with Doruksen.","assets/media/doruksen-01.webp"],
 ["Datsko at The Prince","Some favourite moments from a sold-out show with Datsko.","assets/media/datsko-01.webp"],
 ["Teletech x Stamina After Party · 25.04.26","Burjoe, Kiara Friend, Elsewhere, Mitro and Panic across two rooms.","photo-1492684223066-81342ee5ff30"],
 ["Teletech x Stamina After Party · 11.10.25","Nik Sitz, Goumar, Four To Eight and Elsewhere headline a stacked bill.","photo-1506157786151-b8491531f063"],
 ["TeleTech x Nerve Australia After Party","Official Teletech Australia After Party at Brown Alley, Melbourne.","photo-1524368535928-5b5e00ddc76b"],
 ["Stamina — Every Saturday","Melbourne's home for hard techno and high-energy lineups at Platform One.","photo-1514525253161-7a46d19cd819"],
 ["Nerve — Every Friday","A Melbourne collective built around raw, underground sound at Brown Alley.","photo-1501386761578-eac5c94b800a"]
];
const url=(id,w=1200)=>id.startsWith("assets/")?id:`https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=85`;
document.querySelector('#featured-events').innerHTML=events.map(e=>`<article class="event-card"><div class="event-photo"><img src="${url(e.image,1000)}" alt="${e.name}" loading="lazy"><span class="event-label">${e.tag}</span></div><div class="event-info"><h3>${e.name}</h3>${e.soldOut?`<span class="buy-link sold-out">SOLD OUT</span>`:`<a class="buy-link" href="${e.link}" target="_blank" rel="noreferrer">BUY TICKETS ↗</a>`}<p>${e.desc}</p></div></article>`).join('');
document.querySelector('#event-archive').innerHTML=past.slice(0,6).map(e=>`<article class="archive-card"><img src="${url(e[2],650)}" alt="${e[0]}" loading="lazy"><div class="archive-overlay"><small>ASHBY PROJECTS / ARCHIVE</small><h4>${e[0]}</h4><p>${e[1]}</p></div></article>`).join('');
const tourArtists=[
 {name:"AREA ØNE",images:["photo-1470229722913-7c0e2dbbafd3","photo-1506157786151-b8491531f063","photo-1492684223066-81342ee5ff30"],desc:"Touring with Ashby Projects. For booking enquiries, contact Matthew."},
 {name:"THISO",images:["photo-1501386761578-eac5c94b800a","photo-1571266028243-d220c9c3b6b2","photo-1514525253161-7a46d19cd819"],desc:"Touring with Ashby Projects. For booking enquiries, contact Matthew."},
 {name:"niotech",images:["photo-1506157786151-b8491531f063","photo-1470229722913-7c0e2dbbafd3","photo-1501386761578-eac5c94b800a"],desc:"Touring with Ashby Projects. For booking enquiries, contact Matthew."}
];
let slideIndexes=[0,0,0];
const drawTour=()=>{document.querySelector('#tour-list').innerHTML=tourArtists.map((a,i)=>`<article class="tour-card"><div class="tour-image"><img src="${url(a.images[slideIndexes[i]],900)}" alt="${a.name} live" loading="lazy"><span class="tour-count">0${slideIndexes[i]+1} / 0${a.images.length}</span><div class="tour-controls"><button aria-label="Previous ${a.name} image" data-tour="${i}" data-dir="-1">←</button><button aria-label="Next ${a.name} image" data-tour="${i}" data-dir="1">→</button></div></div><div class="tour-info"><h3 class="tour-name">${a.name}</h3><p>${a.desc}</p></div></article>`).join('');document.querySelectorAll('[data-tour]').forEach(b=>b.onclick=()=>{let i=+b.dataset.tour;slideIndexes[i]=(slideIndexes[i]+ +b.dataset.dir+tourArtists[i].images.length)%tourArtists[i].images.length;drawTour()})};drawTour();
const artists=["Brianna Baxter","Panic","Four To Eight"];
const artistPhotos=["photo-1506157786151-b8491531f063","photo-1470229722913-7c0e2dbbafd3","assets/media/fourtoeight-01.jpg"];
const descriptions={"Brianna Baxter":"Managed by Ashby Projects. For artist enquiries, get in touch with our team.","Panic":"Managed by Ashby Projects. For artist enquiries, get in touch with our team.","Four To Eight":"Managed by Ashby Projects. For artist enquiries, get in touch with our team."};
document.querySelector('#artist-grid').innerHTML=artists.map((a,i)=>`<button class="artist-card" data-artist="${a}" aria-label="Learn more about ${a}"><img src="${url(artistPhotos[i],700)}" alt="Live event photography" loading="lazy"><span class="artist-type">ARTIST MANAGEMENT</span><span class="artist-name"><span>${a}</span></span></button>`).join('');
const dlg=document.querySelector('#artist-dialog');document.querySelectorAll('[data-artist]').forEach(btn=>btn.onclick=()=>{const name=btn.dataset.artist;dlg.querySelector('.dialog-photo').style.backgroundImage=`url('${url(artistPhotos[artists.indexOf(name)],900)}')`;dlg.querySelector('h2').textContent=name;dlg.querySelector('.dialog-info p').textContent=descriptions[name];dlg.showModal()});dlg.querySelector('.dialog-close').onclick=()=>dlg.close();dlg.onclick=e=>{if(e.target===dlg)dlg.close()};
const toggle=document.querySelector(".menu-toggle"),nav=document.querySelector(".main-nav");let closeTimer;function setMenu(open){clearTimeout(closeTimer);toggle.setAttribute("aria-expanded",open);toggle.setAttribute("aria-label",open?"Close navigation":"Open navigation");toggle.querySelector("span").textContent=open?"Close":"Menu";document.body.classList.toggle("menu-is-open",open);if(open){nav.classList.remove("is-closing");nav.classList.add("mobile-open")}else if(nav.classList.contains("mobile-open")){nav.classList.add("is-closing");closeTimer=setTimeout(()=>{nav.classList.remove("mobile-open","is-closing")},680)}}toggle.onclick=()=>setMenu(toggle.getAttribute("aria-expanded")!=="true");nav.querySelectorAll("a").forEach(link=>link.addEventListener("click",event=>{const href=link.getAttribute("href");if(href&&href.startsWith("#")){event.preventDefault();setMenu(false);closeTimer=setTimeout(()=>{location.hash=href},280)}else setMenu(false)}));document.addEventListener("keydown",event=>{if(event.key==="Escape"&&toggle.getAttribute("aria-expanded")==="true")setMenu(false)});nav.addEventListener("click",event=>{if(event.target===nav)setMenu(false)});
